version: "3.3"

services:
  nginx:
    image: nginx:1.19.7-alpine
    container_name: ak-nginx
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf


  app:
    build:
      context: app
      dockerfile: Dockerfile.dev
    container_name: ak-app
    command: npm run dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app