version: "3.3"

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile.dev
    container_name: ak-app
    command: npm run dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app