version: "3.3"

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile.prod
    command: npm run dev
    ports:
      - 3000:3000
    container_name: ak-app
    volumes:
      - ./app:/app