version: "3.3"

services:
  about:
    build:
      context: app
      dockerfile: Dockerfile.dev
    container_name: ak-about
    command: npm run dev
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 80:3000
    volumes:
      - ./about:/app