FROM node:14.15.3-alpine3.12
WORKDIR /app
ADD package.json package.json
RUN npm install
ADD . .
ENV NODE_ENV production
RUN npm i -g next
RUN npm i -g react
RUN npm i -g react-dom
RUN npm i -g react-redux
#RUN npm run build
EXPOSE 3000