FROM node:14.15.3-alpine3.12
WORKDIR /app
COPY package*.json ./

# Поставить все пакеты из package.json
# Поставить сервер
RUN npm install

# Скопировать все остальные файлы
COPY . .

# Собрать пакет
RUN npm run build
RUN npm run start